### PR TITLE
remove OS specific and temporary files

### PR DESCRIPTION
**Pull request by Cube707**
have fun

### CODE REVIEW

**Review by JalilRasooly — COMMENTED** [review]
Hi Cube707, 
Thank you so much for your contribution! As a new user on GitHub, I truly appreciate your helpful input. It's great to see such a supportive community here.

**Review by JalilRasooly — COMMENTED** [review]
Hi Cube707,
Thank you so much for your contribution! As a new user on GitHub, I truly appreciate your helpful input. It's great to see such a supportive community here.

**Comment by Cube707** [comment]
Yea no problem. But I bodged something and modified all your old commits. Thats why I closed it against 

Maybe I can find the time to fix it later

**Comment by JalilRasooly** [comment]
that would be greate !

**Pull request closed without merging**
